apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-staging
  labels:
    app: user-service-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-staging
  template:
    metadata:
      labels:
        app: user-service-staging
    spec:
      containers:
        - name: user-service
          image: host.minikube.internal:5000/user_service_staging # Replace with your Docker image
          ports:
            - containerPort: 8000
          env:
            - name: DB_DRIVER_DEV
              value: 'ODBC Driver 17 for SQL Server'
            - name: DB_SERVER_DEV
              valueFrom:
                configMapKeyRef:
                  name: fyp-config
                  key: DB_SERVER_STG
            - name: DB_DATABASE_DEV
              value: 'user_service_dev'
            - name: DB_DATABASE_PORT
              value: '1433'
            - name: DB_USERNAME_DEV
              value: 'sa'
            - name: DB_PASSWORD_DEV
              value: 'Fyppear@2'
            - name: WEB_FE_ORIGIN
              value: '10.96.188.171:5173'
            - name: WEB_FE_ORIGIN_STAGING
              value: '10.96.188.185:5173'
            - name: REFRESH_SECRET_KEY
              value: 'FakeKey2'
            - name: MAIL_USERNAME
              value: 'fyppear.backend3@gmail.com'
            - name: MAIL_FROM
              value: 'fyppear.backend3@gmail.com'
            - name: MAIL_PORT
              value: '587'
            - name: MAIL_SERVER
              value: 'smtp.gmail.com'
            - name: MAIL_STARTTLS
              value: 'True'
            - name: MAIL_SSL_TLS
              value: 'False'
            - name: MAIL_FROM_NAME
              value: 'PEAR_FYP'
            - name: USE_CREDENTIALS
              value: 'True'
            - name: VALIDATE_CERTS
              value: 'True'
            - name: SALT
              value: 'email-confirmation-salt'
            - name: SECRET_KEY
              value: 'FakeKey'
            - name: OTP_EMAIL
              value: 'fyp_pear@techdevglobal.com'
            - name: ACCESS_TOKEN_EXPIRE_MINUTES 
              value: '15'
            - name: REFRESH_TOKEN_EXPIRE_MINUTES
              value: '120'
            - name: SESSION_EXPIRE_MINUTES
              value: '10'
            - name: EMAIL_LINK_BASEURL
              value: 'http://10.96.188.171:5173'
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-staging
spec:
  selector:
    app: user-service-staging
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000 # Specify the NodePort here
  type: NodePort