apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-staging
  labels:
    app: user-service-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-staging
  template:
    metadata:
      labels:
        app: user-service-staging
    spec:
      containers:
        - name: user-service
          image: host.minikube.internal:5000/user_service_staging
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs  # Path inside the container
      volumes:
        - name: log-volume
          hostPath:
            path: /home/VMadmin/FYP_microservices/PEAR_user_service/logs  # Path on the host machine
            type: DirectoryOrCreate  # Ensures directory is created if it doesn’t exist
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-staging
spec:
  selector:
    app: user-service-staging
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort