apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: filestream
        id: pear-user-service-logs
        enabled: true
        paths:
          - /home/VMadmin/FYP_microservices/PEAR_user_service/logs/*.log
        ignore_older: 24h
        
    logging.level: warning
    
    output.logstash:
      hosts: ["192.168.188.172:5044"]