apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: filestream
        enabled: true
        paths:
          - /home/VMadmin/FYP_microservices/PEAR_user_service/logs/*.log
        ignore_older: 24h

        parsers:
          - ndjson:
              keys_under_root: true          # Put all JSON fields at root level
              add_error_key: true            # Add error field if parsing fails
              message_key: message           # Field containing the JSON string
              overwrite_keys: true           # Overwrite existing top-level keys if duplicated

    logging.level: warning

    output.logstash:
      hosts: ["192.168.188.184:5044"]
