# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, user]

    env:
      DB_SERVER_DEV: ${{ secrets.DB_SERVER_DEV }}
      DB_DATABASE_DEV: ${{ secrets.DB_DATABASE_DEV }}
      DB_DATABASE_PORT: ${{ secrets.DB_DATABASE_PORT }}
      DB_USERNAME_DEV: ${{ secrets.DB_USERNAME_DEV }}
      DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD_DEV }}
      SENDPULSE_API_KEY: ${{ secrets.SENDPULSE_API_KEY }}
      SENDPULSE_SECRET_KEY: ${{ secrets.SENDPULSE_SECRET_KEY }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      WEB_FE_ORIGIN: "${{ secrets.WEB_FE_ORIGIN }}"
      REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_FROM: ${{ secrets.MAIL_FROM }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
      MAIL_STARTTLS: ${{ secrets.MAIL_STARTTLS }}
      MAIL_SSL_TLS: ${{ secrets.MAIL_SSL_TLS }}
      MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
      USE_CREDENTIALS: ${{ secrets.USE_CREDENTIALS }}
      VALIDATE_CERTS: ${{ secrets.VALIDATE_CERTS }}
      SALT: ${{ secrets.SALT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      OTP_EMAIL: ${{ secrets.OTP_EMAIL }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${{ secrets.REFRESH_TOKEN_EXPIRE_MINUTES }}
      SESSION_EXPIRE_MINUTES: ${{ secrets.SESSION_EXPIRE_MINUTES }}
      EMAIL_LINK_BASEURL: ${{ secrets.EMAIL_LINK_BASEURL }}
      
    steps:
      - uses: actions/checkout@v4
      - name: Print working directory
        run: |
          pwd
          ls -la
          git status

      - name: Create .env file from GitHub Secrets
        run: |
          echo "DB_SERVER_DEV=${{ secrets.DB_SERVER_DEV }}" >> .env
          echo "DB_DATABASE_DEV=${{ secrets.DB_DATABASE_DEV }}" >> .env
          echo "DB_DATABASE_PORT=${{ secrets.DB_DATABASE_PORT }}" >> .env
          echo "DB_USERNAME_DEV=${{ secrets.DB_USERNAME_DEV }}" >> .env
          echo "DB_PASSWORD_DEV=${{ secrets.DB_PASSWORD_DEV }}" >> .env
          echo "DB_DRIVER_DEV=${{ secrets.DB_DRIVER_DEV }}" >> .env
          echo "SENDPULSE_API_KEY=${{ secrets.SENDPULSE_API_KEY }}" >> .env
          echo "SENDPULSE_SECRET_KEY=${{ secrets.SENDPULSE_SECRET_KEY }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "WEB_FE_ORIGIN="${{ secrets.WEB_FE_ORIGIN }}"" >> .env
          echo "REFRESH_SECRET_KEY=${{ secrets.REFRESH_SECRET_KEY }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_FROM=${{ secrets.MAIL_FROM }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "MAIL_STARTTLS=${{ secrets.MAIL_STARTTLS }}" >> .env
          echo "MAIL_SSL_TLS=${{ secrets.MAIL_SSL_TLS }}" >> .env
          echo "MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}" >> .env
          echo "USE_CREDENTIALS=${{ secrets.USE_CREDENTIALS }}" >> .env
          echo "VALIDATE_CERTS=${{ secrets.VALIDATE_CERTS }}" >> .env
          echo "SALT=${{ secrets.SALT }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "OTP_EMAIL=${{ secrets.OTP_EMAIL }}" >> .env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env
          echo "REFRESH_TOKEN_EXPIRE_MINUTES=${{ secrets.REFRESH_TOKEN_EXPIRE_MINUTES }}" >> .env
          echo "SESSION_EXPIRE_MINUTES=${{ secrets.SESSION_EXPIRE_MINUTES }}" >> .env
          echo "EMAIL_LINK_BASEURL=${{ secrets.EMAIL_LINK_BASEURL }}" >> .env

      - name: Delete old deployment
        run: |
          echo "Deleting old deployment..."
          kubectl delete deployment.apps/user-service-dev service/user-service-dev

      - name: Delete old docker images
        run: |
          docker rmi user_service_dev
          docker rmi localhost:5000/user_service_dev

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build --no-cache -f Dockerfile.dev -t user_service_dev .

      - name: Tag Docker image
        run: |
          echo "Tagging Docker image..."
          docker tag user_service_dev:latest localhost:5000/user_service_dev:latest

      - name: Push Docker image to local registry
        run: |
          echo "Pushing Docker image to localhost:5000...."
          docker push localhost:5000/user_service_dev:latest

      - name: Deploying to Kubernetes
        run: |
          echo "Deploying..."
          kubectl apply -f './k8s/deployment-dev.yaml'
