# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  pull_request:
    branches: ['**']
  

jobs:
  ci-staging:
    # This will be the default CI job for everything except for Main branch.
    uses: ./.github/workflows/base-ci.yml
    secrets: inherit
    with:
      environment: 'staging'
      runner-label: 'user'
      python-version: '3.9.19'


  ci-prod:
    if: github.base_ref == 'main' && github.event_name == 'pull_request'
    uses: ./.github/workflows/base-ci.yml
    secrets: inherit
    with:
      environment: 'main'
      runner-label: 'user_prod'
      python-version: '3.9.19'
